-- Navadrishti Supabase schema
-- Source: completeschema.txt
-- Generated to be runnable in Supabase SQL Editor
-- Date: 2026-03-12

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.hashtags (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  tag character varying NOT NULL UNIQUE,
  total_mentions integer DEFAULT 0,
  weekly_mentions integer DEFAULT 0,
  daily_mentions integer DEFAULT 0,
  trending_score numeric DEFAULT 0,
  category character varying DEFAULT 'general'::character varying,
  is_trending boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT hashtags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.platform_announcements (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('announcement', 'changelog')),
  title TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.system_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying CHECK (type::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'error'::character varying, 'success'::character varying]::text[])),
  target_audience character varying DEFAULT 'all'::character varying CHECK (target_audience::text = ANY (ARRAY['all'::character varying, 'users'::character varying, 'companies'::character varying, 'ngos'::character varying, 'admins'::character varying]::text[])),
  is_active boolean DEFAULT true,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  admin_user_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trending_topics (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  topic character varying NOT NULL UNIQUE,
  category character varying,
  mention_count integer DEFAULT 1,
  unique_users_count integer DEFAULT 1,
  trend_score numeric DEFAULT 0.0,
  last_mentioned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trending_topics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  user_type text NOT NULL,
  name character varying NOT NULL,
  phone character varying,
  location character varying,
  verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  two_factor_enabled boolean DEFAULT false,
  two_factor_secret character varying,
  account_status text DEFAULT 'pending_verification',
  last_login timestamp with time zone,
  login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  timezone character varying DEFAULT 'UTC'::character varying,
  preferences jsonb,
  privacy_settings jsonb,
  verification_status text DEFAULT 'unverified',
  verification_level text DEFAULT 'basic',
  verified_at timestamp with time zone,
  identity_verified boolean DEFAULT false,
  city character varying,
  state_province character varying,
  pincode character varying,
  country character varying DEFAULT 'India'::character varying,
  email_verified_at timestamp without time zone,
  phone_verified_at timestamp without time zone,
  age integer,
  work_experience text,
  industry character varying,
  website character varying,
  company_size character varying,
  ngo_size character varying,
  profile_image text,
  profile_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.activity_feed (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  activity_type character varying NOT NULL,
  entity_type character varying,
  entity_id integer,
  activity_data json,
  visibility character varying DEFAULT 'public'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT activity_feed_pkey PRIMARY KEY (id),
  CONSTRAINT activity_feed_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.company_verifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL UNIQUE,
  company_name character varying,
  registration_number character varying,
  gst_number character varying,
  verification_status character varying DEFAULT 'unverified'::character varying,
  verification_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT company_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT company_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.ecommerce_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  order_number character varying NOT NULL UNIQUE,
  buyer_id bigint NOT NULL,
  seller_id bigint NOT NULL,
  total_amount numeric NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'processing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  shipping_address jsonb NOT NULL,
  billing_address jsonb,
  order_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ecommerce_orders_pkey PRIMARY KEY (id),
  CONSTRAINT ecommerce_orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(id),
  CONSTRAINT ecommerce_orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.email_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT email_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.enhanced_suggestions_cache (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  suggestion_type character varying NOT NULL,
  suggestion_data json NOT NULL,
  generated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP + '02:00:00'::interval),
  cache_key character varying,
  CONSTRAINT enhanced_suggestions_cache_pkey PRIMARY KEY (id),
  CONSTRAINT enhanced_suggestions_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.individual_verifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL UNIQUE,
  aadhaar_number character varying,
  aadhaar_verified boolean DEFAULT false,
  aadhaar_verification_date timestamp without time zone,
  pan_number character varying,
  pan_verified boolean DEFAULT false,
  pan_verification_date timestamp without time zone,
  verification_status character varying DEFAULT 'unverified'::character varying,
  verification_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT individual_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT individual_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.login_history (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  ip_address inet,
  user_agent text,
  login_method character varying DEFAULT 'email'::character varying,
  success boolean DEFAULT true,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT login_history_pkey PRIMARY KEY (id),
  CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.marketplace_items (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  seller_id integer NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  subcategory character varying,
  condition_type text NOT NULL,
  item_type text NOT NULL,
  quantity integer DEFAULT 1,
  price numeric NOT NULL,
  compare_price numeric,
  original_price numeric,
  tags jsonb,
  location character varying,
  images jsonb,
  weight_kg numeric DEFAULT 1.00,
  dimensions_cm jsonb,
  status text DEFAULT 'active',
  rating_average numeric DEFAULT 0.0,
  rating_count integer DEFAULT 0,
  is_negotiable boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contact_info jsonb,
  views_count integer DEFAULT 0,
  featured boolean DEFAULT false,
  brand character varying,
  specifications jsonb,
  features jsonb,
  city character varying,
  state_province character varying,
  pincode character varying,
  country character varying DEFAULT 'India'::character varying,
  who_can_buy text[] NOT NULL DEFAULT ARRAY['ngo'::text, 'individual'::text, 'company'::text] CHECK (who_can_buy <@ ARRAY['ngo'::text, 'individual'::text, 'company'::text] AND array_length(who_can_buy, 1) > 0),
  sold_at timestamp without time zone,
  CONSTRAINT marketplace_items_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.ngo_verifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL UNIQUE,
  ngo_name character varying,
  registration_number character varying,
  registration_type character varying,
  fcra_number character varying,
  verification_status character varying DEFAULT 'unverified'::character varying,
  verification_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ngo_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT ngo_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.otp_verifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  contact character varying NOT NULL,
  otp_code character varying NOT NULL,
  verification_type character varying NOT NULL CHECK (verification_type::text = ANY (ARRAY['email'::character varying, 'phone'::character varying]::text[])),
  is_verified boolean DEFAULT false,
  attempts integer DEFAULT 0,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  verified_at timestamp without time zone,
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT otp_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.phone_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  phone character varying NOT NULL,
  otp character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT phone_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT phone_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  author_id integer NOT NULL,
  content text NOT NULL,
  post_type text DEFAULT 'text',
  media_urls jsonb,
  media_metadata jsonb,
  visibility text DEFAULT 'public',
  allow_comments boolean DEFAULT true,
  allow_reactions boolean DEFAULT true,
  is_pinned boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  reaction_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  view_count integer DEFAULT 0,
  tags jsonb,
  mentioned_users jsonb,
  category character varying,
  location character varying,
  organization_context jsonb,
  is_flagged boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  flagged_reason text,
  moderated_at timestamp with time zone,
  moderated_by integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone DEFAULT now(),
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT posts_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.service_offers (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  ngo_id integer NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  skills_offered jsonb,
  pricing_info jsonb,
  availability jsonb,
  location character varying,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_status text DEFAULT 'pending',
  admin_reviewed_at timestamp with time zone,
  admin_reviewed_by integer,
  admin_comments text,
  submitted_for_review_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_offers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_service_offers_admin_reviewed_by FOREIGN KEY (admin_reviewed_by) REFERENCES public.users(id),
  CONSTRAINT service_offers_ngo_id_fkey FOREIGN KEY (ngo_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.service_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  ngo_id integer NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  tags jsonb,
  urgency_level text DEFAULT 'medium',
  volunteers_needed integer DEFAULT 1,
  priority text DEFAULT 'medium',
  deadline date,
  location character varying,
  requirements jsonb,
  image_url character varying,
  status text DEFAULT 'active',
  volunteer_limit integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  timeline character varying,
  contact_info text,
  CONSTRAINT service_requests_pkey PRIMARY KEY (id),
  CONSTRAINT service_requests_ngo_id_fkey FOREIGN KEY (ngo_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  name character varying NOT NULL,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city character varying NOT NULL,
  state character varying NOT NULL,
  pincode character varying NOT NULL,
  country character varying DEFAULT 'India'::character varying,
  phone character varying NOT NULL,
  address_type character varying DEFAULT 'home'::character varying CHECK (address_type::text = ANY (ARRAY['home'::character varying, 'work'::character varying, 'other'::character varying]::text[])),
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  follower_id integer NOT NULL,
  following_id integer NOT NULL,
  connection_type character varying DEFAULT 'follow'::character varying,
  status character varying DEFAULT 'active'::character varying,
  relationship_note text,
  interaction_level integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_connections_pkey PRIMARY KEY (id),
  CONSTRAINT user_connections_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.users(id),
  CONSTRAINT user_connections_following_id_fkey FOREIGN KEY (following_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_feed_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL UNIQUE,
  show_achievements boolean DEFAULT true,
  show_opportunities boolean DEFAULT true,
  show_updates boolean DEFAULT true,
  show_events boolean DEFAULT true,
  show_individual_posts boolean DEFAULT true,
  show_ngo_posts boolean DEFAULT true,
  show_company_posts boolean DEFAULT true,
  auto_follow_back boolean DEFAULT false,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  preferred_categories jsonb,
  muted_keywords jsonb,
  preferred_languages jsonb,
  profile_visibility text DEFAULT 'public',
  activity_visibility text DEFAULT 'public',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_feed_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_feed_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_interests (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  interest_type character varying NOT NULL,
  interest_value character varying NOT NULL,
  interest_score numeric DEFAULT 1.0,
  source character varying DEFAULT 'implicit'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_interests_pkey PRIMARY KEY (id),
  CONSTRAINT user_interests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id integer NOT NULL,
  user_type text NOT NULL,
  session_data jsonb NOT NULL,
  ip_address inet,
  user_agent text,
  device_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.cart (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  marketplace_item_id integer NOT NULL,
  quantity integer DEFAULT 1,
  variant_selection jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_pkey PRIMARY KEY (id),
  CONSTRAINT cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cart_marketplace_item_id_fkey FOREIGN KEY (marketplace_item_id) REFERENCES public.marketplace_items(id)
);

CREATE TABLE IF NOT EXISTS public.ecommerce_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  order_id bigint NOT NULL,
  marketplace_item_id bigint NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  item_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ecommerce_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT ecommerce_order_items_marketplace_item_id_fkey FOREIGN KEY (marketplace_item_id) REFERENCES public.marketplace_items(id),
  CONSTRAINT ecommerce_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.ecommerce_orders(id)
);

CREATE TABLE IF NOT EXISTS public.ecommerce_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  order_id bigint NOT NULL,
  amount numeric NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_method character varying,
  razorpay_order_id character varying,
  razorpay_payment_id character varying,
  razorpay_signature character varying,
  captured_at timestamp with time zone,
  refunded_at timestamp with time zone,
  refund_amount numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ecommerce_payments_pkey PRIMARY KEY (id),
  CONSTRAINT ecommerce_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.ecommerce_orders(id)
);

CREATE TABLE IF NOT EXISTS public.ecommerce_shipping_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  order_id bigint NOT NULL,
  tracking_status character varying DEFAULT 'pending'::character varying CHECK (tracking_status::text = ANY (ARRAY['pending'::character varying, 'picked_up'::character varying, 'in_transit'::character varying, 'out_for_delivery'::character varying, 'delivered'::character varying, 'returned'::character varying]::text[])),
  courier_partner character varying,
  delhivery_waybill character varying,
  tracking_number character varying,
  shipped_at timestamp with time zone,
  expected_delivery timestamp with time zone,
  actual_delivery timestamp with time zone,
  delivery_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ecommerce_shipping_details_pkey PRIMARY KEY (id),
  CONSTRAINT ecommerce_shipping_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.ecommerce_orders(id)
);

CREATE TABLE IF NOT EXISTS public.hashtag_usage (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  hashtag_id integer NOT NULL,
  post_id integer NOT NULL,
  user_id integer NOT NULL,
  usage_context character varying DEFAULT 'post'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT hashtag_usage_pkey PRIMARY KEY (id),
  CONSTRAINT hashtag_usage_hashtag_id_fkey FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(id),
  CONSTRAINT hashtag_usage_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);

CREATE TABLE IF NOT EXISTS public.post_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  post_id bigint NOT NULL,
  date date NOT NULL,
  views_count integer DEFAULT 0,
  unique_viewers_count integer DEFAULT 0,
  reactions_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  shares_count integer DEFAULT 0,
  engagement_rate numeric DEFAULT 0.0,
  reach_count integer DEFAULT 0,
  impression_count integer DEFAULT 0,
  audience_breakdown jsonb,
  geographic_breakdown jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT post_analytics_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);

CREATE TABLE IF NOT EXISTS public.post_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  post_id bigint NOT NULL,
  author_id integer NOT NULL,
  parent_comment_id bigint,
  content text NOT NULL,
  media_urls jsonb,
  mentioned_users jsonb,
  reaction_count integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  status text DEFAULT 'active',
  is_flagged boolean DEFAULT false,
  flagged_reason text,
  moderated_at timestamp with time zone,
  moderated_by integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_comments_pkey PRIMARY KEY (id),
  CONSTRAINT post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT post_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.post_comments(id),
  CONSTRAINT post_comments_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.post_interactions (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  post_id integer NOT NULL,
  user_id integer NOT NULL,
  interaction_type character varying NOT NULL,
  interaction_value integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT post_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT post_interactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);

CREATE TABLE IF NOT EXISTS public.post_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  post_id bigint NOT NULL,
  user_id integer NOT NULL,
  reaction_type text DEFAULT 'like',
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT post_reactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.post_shares (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  post_id bigint NOT NULL,
  shared_by integer NOT NULL,
  share_type character varying DEFAULT 'repost'::character varying,
  share_message text,
  platform character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_shares_pkey PRIMARY KEY (id),
  CONSTRAINT post_shares_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.service_clients (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  service_offer_id integer NOT NULL,
  client_id integer NOT NULL,
  message text,
  proposed_amount numeric,
  proposed_start_date date,
  status character varying DEFAULT 'pending'::character varying,
  applied_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expected_beneficiaries integer,
  project_timeline text,
  start_date date,
  end_date date,
  CONSTRAINT service_clients_pkey PRIMARY KEY (id),
  CONSTRAINT service_clients_service_offer_id_fkey FOREIGN KEY (service_offer_id) REFERENCES public.service_offers(id),
  CONSTRAINT service_clients_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.service_volunteers (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  service_request_id integer NOT NULL,
  volunteer_id integer NOT NULL,
  application_message text,
  status character varying DEFAULT 'pending'::character varying,
  applied_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  volunteer_hours numeric,
  team_size integer DEFAULT 1,
  team_members text,
  impact_statement text,
  estimated_impact_value numeric,
  CONSTRAINT service_volunteers_pkey PRIMARY KEY (id),
  CONSTRAINT service_volunteers_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT service_volunteers_volunteer_id_fkey FOREIGN KEY (volunteer_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.wishlist (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  marketplace_item_id integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT wishlist_marketplace_item_id_fkey FOREIGN KEY (marketplace_item_id) REFERENCES public.marketplace_items(id)
);

CREATE TABLE IF NOT EXISTS public.comment_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  comment_id bigint NOT NULL,
  user_id integer NOT NULL,
  reaction_type text DEFAULT 'like',
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comment_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT comment_reactions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.post_comments(id),
  CONSTRAINT comment_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.marketplace_item_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  marketplace_item_id integer NOT NULL,
  reviewer_id integer NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  review_text text NOT NULL,
  verified_purchase boolean DEFAULT false,
  purchase_id integer,
  status character varying DEFAULT 'published'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'published'::character varying, 'flagged'::character varying, 'removed'::character varying]::text[])),
  helpful_count integer DEFAULT 0,
  unhelpful_count integer DEFAULT 0,
  flagged_reason text,
  reviewed_by_admin boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  images jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT marketplace_item_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_item_reviews_marketplace_item_id_fkey FOREIGN KEY (marketplace_item_id) REFERENCES public.marketplace_items(id),
  CONSTRAINT marketplace_item_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT marketplace_item_reviews_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES public.ecommerce_order_items(id)
);

CREATE TABLE IF NOT EXISTS public.user_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text,
  related_user_id integer,
  related_post_id bigint,
  related_comment_id bigint,
  is_read boolean DEFAULT false,
  is_seen boolean DEFAULT false,
  action_url character varying,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  seen_at timestamp with time zone,
  CONSTRAINT user_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_notifications_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES public.users(id),
  CONSTRAINT user_notifications_related_post_id_fkey FOREIGN KEY (related_post_id) REFERENCES public.posts(id),
  CONSTRAINT user_notifications_related_comment_id_fkey FOREIGN KEY (related_comment_id) REFERENCES public.post_comments(id)
);

COMMIT;
