import { PRODUCT_NAME, COMPANY_LEGAL_NAME } from '@/lib/access-control'

export const DOCUMENT_DISCLAIMER =
  `Generated by ${PRODUCT_NAME} (${COMPANY_LEGAL_NAME}) from platform records as of the generation timestamp. This is an operational / board-working document for internal CSR, funder, and partner use. It is not an MCA e-filing, not Form CSR-1 or Form CSR-2, and not a substitute for statutory certificates (12A, 80G, FCRA) or CA-signed legal opinions.`

export type DocumentChromeOptions = {
  title: string
  subtitle?: string
  documentCode: string
  generatedAt?: Date
  rightMeta?: string
  classification?: string
  version?: string
  referenceNumber?: string
}

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function formatInr(amount: number | null | undefined): string {
  const n = Number(amount)
  if (!Number.isFinite(n)) return '—'
  return `₹${n.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
}

export function formatDisplayDate(value?: string | Date | null): string {
  if (!value) return '—'
  const date = value instanceof Date ? value : new Date(value)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  })
}

export function buildDocumentReference(prefix: string, orgKey: string): string {
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '')
  const slug = String(orgKey || 'ORG')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '')
    .slice(0, 12) || 'ORG'
  return `${prefix}/${slug}/${stamp}`
}

const SHARED_STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', Calibri, Arial, sans-serif;
    background: #ffffff;
    color: #111827;
    padding: 48px 56px;
    font-size: 12.5px;
    line-height: 1.55;
  }
  .brand-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
    font-size: 10px;
    color: #64748b;
    letter-spacing: 0.3px;
    text-transform: uppercase;
  }
  .brand-bar strong { color: #0f172a; font-size: 12px; letter-spacing: 0.6px; }
  .doc-control {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 18px;
    font-size: 10px;
  }
  .doc-control th, .doc-control td {
    border: 1px solid #cbd5e1;
    padding: 7px 10px;
    text-align: left;
  }
  .doc-control th {
    background: #f1f5f9;
    width: 18%;
    color: #475569;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.6px;
  }
  .header {
    border-bottom: 2px solid #0f172a;
    padding-bottom: 16px;
    margin-bottom: 16px;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    gap: 24px;
  }
  .header-left h1 {
    font-size: 20px;
    font-weight: 700;
    letter-spacing: 0.2px;
    color: #0f172a;
  }
  .header-left p { font-size: 11px; color: #64748b; margin-top: 4px; }
  .header-right { text-align: right; font-size: 11px; color: #64748b; }
  .classification {
    display: inline-block;
    margin-top: 6px;
    padding: 3px 8px;
    border: 1px solid #94a3b8;
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #334155;
  }
  .disclaimer {
    margin-bottom: 22px;
    padding: 10px 12px;
    border-left: 3px solid #64748b;
    background: #f8fafc;
    font-size: 10px;
    color: #475569;
    line-height: 1.5;
  }
  .section { margin-bottom: 24px; page-break-inside: avoid; }
  .section-title {
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.8px;
    text-transform: uppercase;
    color: #0f172a;
    margin-bottom: 10px;
    padding-bottom: 5px;
    border-bottom: 1px solid #e2e8f0;
  }
  .section-intro { color: #64748b; font-size: 11px; margin-bottom: 10px; }
  .field-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px 24px;
  }
  .field-grid-3 {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 12px;
  }
  .field { display: flex; flex-direction: column; gap: 2px; }
  .field-label {
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 0.7px;
    text-transform: uppercase;
    color: #64748b;
  }
  .field-value { font-size: 13px; color: #0f172a; font-weight: 600; word-break: break-word; }
  .muted { color: #64748b; font-size: 11px; }
  .metric-card {
    border: 1px solid #e2e8f0;
    background: #f8fafc;
    padding: 12px 14px;
  }
  .metric-card .field-value { font-size: 15px; }
  .table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 8px;
    font-size: 11.5px;
  }
  .table th, .table td {
    border: 1px solid #cbd5e1;
    padding: 8px 9px;
    text-align: left;
    vertical-align: top;
  }
  .table th {
    background: #f1f5f9;
    font-size: 9px;
    letter-spacing: 0.6px;
    text-transform: uppercase;
    color: #475569;
  }
  .badge {
    display: inline-block;
    padding: 3px 8px;
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 0.7px;
    text-transform: uppercase;
  }
  .badge-ok { background: #ecfdf5; color: #047857; border: 1px solid #a7f3d0; }
  .badge-warn { background: #fffbeb; color: #b45309; border: 1px solid #fde68a; }
  .badge-info { background: #eff6ff; color: #1d4ed8; border: 1px solid #bfdbfe; }
  .gaps {
    border: 1px solid #f59e0b;
    background: #fffbeb;
    padding: 10px 12px;
    font-size: 11px;
    color: #92400e;
  }
  .gaps ul { margin: 6px 0 0 16px; }
  .signature-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 28px;
    margin-top: 18px;
  }
  .signature-box {
    border-top: 1px solid #94a3b8;
    padding-top: 10px;
    min-height: 72px;
  }
  .signature-box .role {
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: #475569;
  }
  .signature-box .hint { font-size: 10px; color: #94a3b8; margin-top: 28px; }
  .footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #cbd5e1;
    display: flex;
    justify-content: space-between;
    gap: 16px;
    font-size: 9px;
    color: #94a3b8;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  @media print {
    body { padding: 18mm 16mm; }
    .disclaimer, .section, .signature-grid { break-inside: avoid; }
  }
`

export function renderSignatureBlock(
  roles: Array<{ role: string; hint?: string }> = [
    { role: 'Authorized Signatory', hint: 'Name / Designation / Date' },
    { role: 'Countersignature (if required)', hint: 'CSR Committee Chair / CFO / Partner' },
  ]
): string {
  return `
    <div class="section">
      <div class="section-title">Authorization</div>
      <p class="section-intro">Wet-ink or digital signatures to be affixed by the organization after review. GRAM does not apply statutory signatures.</p>
      <div class="signature-grid">
        ${roles
          .map(
            (item) => `
          <div class="signature-box">
            <div class="role">${escapeHtml(item.role)}</div>
            <div class="hint">${escapeHtml(item.hint || 'Name / Designation / Date')}</div>
          </div>`
          )
          .join('')}
      </div>
    </div>
  `
}

export function wrapDocumentHtml(chrome: DocumentChromeOptions, bodyHtml: string): string {
  const generatedAt = formatDisplayDate(chrome.generatedAt || new Date())
  const version = chrome.version || '1.0'
  const classification = chrome.classification || 'INTERNAL — BOARD / FUNDER WORKING COPY'
  const reference = chrome.referenceNumber || chrome.documentCode

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(chrome.title)}</title>
  <style>${SHARED_STYLES}</style>
</head>
<body>
  <div class="brand-bar">
    <strong>${escapeHtml(PRODUCT_NAME)}</strong>
    <span>Powered by ${escapeHtml(COMPANY_LEGAL_NAME)}</span>
  </div>
  <div class="header">
    <div class="header-left">
      <h1>${escapeHtml(chrome.title)}</h1>
      ${chrome.subtitle ? `<p>${escapeHtml(chrome.subtitle)}</p>` : ''}
      <div class="classification">${escapeHtml(classification)}</div>
    </div>
    <div class="header-right">
      <div>Generated: ${escapeHtml(generatedAt)}</div>
      ${chrome.rightMeta ? `<div>${escapeHtml(chrome.rightMeta)}</div>` : ''}
    </div>
  </div>
  <table class="doc-control">
    <tr>
      <th>Document ID</th>
      <td>${escapeHtml(reference)}</td>
      <th>Version</th>
      <td>${escapeHtml(version)}</td>
    </tr>
    <tr>
      <th>Classification</th>
      <td>${escapeHtml(classification)}</td>
      <th>Source</th>
      <td>${escapeHtml(PRODUCT_NAME)} platform records</td>
    </tr>
  </table>
  <div class="disclaimer">${escapeHtml(DOCUMENT_DISCLAIMER)}</div>
  ${bodyHtml}
  <div class="footer">
    <span>${escapeHtml(PRODUCT_NAME)} Document Generation</span>
    <span>${escapeHtml(chrome.documentCode)}</span>
  </div>
</body>
</html>`
}

export function renderGapsSection(gaps: string[]): string {
  if (!gaps.length) return ''
  return `
    <div class="section">
      <div class="section-title">Data Completeness Notes</div>
      <div class="gaps">
        The following fields were missing or incomplete on the platform. Complete them before board / MCA / funder submission.
        <ul>${gaps.map((gap) => `<li>${escapeHtml(gap)}</li>`).join('')}</ul>
      </div>
    </div>
  `
}
