'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Shield, Loader2, AlertCircle } from 'lucide-react';
import { PortalLoginShell } from '@/components/portal-login-shell';
import { usePortalLoginRedirect } from '@/hooks/use-portal-login-redirect';

export default function CompanyCAPanelLoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const checkingAuth = usePortalLoginRedirect({
    verifyUrl: '/api/companies/ca/verify',
    sessionKey: 'company_ca_tab_session',
    dashboardPath: '/companies/ca',
    changePasswordPath: '/companies/ca/change-password',
  });

  const handleLogin = async (event: React.FormEvent) => {
    event.preventDefault();
    setError('');

    try {
      setLoading(true);
      const response = await fetch('/api/companies/ca/auth', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        credentials: 'include',
        body: JSON.stringify({ email, password })
      });

      const payload = await response.json();
      if (!response.ok || !payload?.success) {
        setError(payload?.error || 'Login failed');
        return;
      }

      try { sessionStorage.setItem('company_ca_tab_session', Date.now().toString()); } catch {}

      if (payload.must_change_password) {
        router.push('/companies/ca/change-password');
      } else {
        router.push('/companies/ca');
      }
    } catch {
      setError('Unable to login. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  if (checkingAuth) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-50 to-blue-100">
        <div className="text-center">
          <Loader2 className="mx-auto h-8 w-8 animate-spin text-blue-600" />
          <p className="mt-4 text-blue-600">Checking authentication...</p>
        </div>
      </div>
    );
  }

  return (
    <PortalLoginShell
      portalTitle="Evidence Verification Portal"
      portalSubtitle="Company Chartered Accountant Access"
      cardDescription="Use credentials generated by your company dashboard"
      footerNote="Company CA Management Portal"
    >
      <form className="space-y-4" onSubmit={handleLogin}>
        {error ? (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : null}

        <div className="space-y-2">
          <Label htmlFor="company-ca-email">Email</Label>
          <Input
            id="company-ca-email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            placeholder="ca@yourcompany.com"
            required
            disabled={loading}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="company-ca-password">Password</Label>
          <Input
            id="company-ca-password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            placeholder="Your password"
            required
            disabled={loading}
          />
        </div>

        <Button type="submit" className="w-full" disabled={loading || !email || !password}>
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Signing in...
            </>
          ) : (
            <>
              <Shield className="mr-2 h-4 w-4" />
              Sign In
            </>
          )}
        </Button>
      </form>
    </PortalLoginShell>
  );
}
