'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import Image from 'next/image';

export default function CompanyCAPanelLoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async (event: React.FormEvent) => {
    event.preventDefault();
    setError('');

    try {
      setLoading(true);
      const response = await fetch('/api/companies/ca/auth', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        credentials: 'include',
        body: JSON.stringify({ email, password })
      });

      const payload = await response.json();
      if (!response.ok || !payload?.success) {
        setError(payload?.error || 'Login failed');
        return;
      }

      router.push('/companies/ca');
    } catch {
      setError('Unable to login. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col items-center justify-center p-6">

      {/* Header */}
      <div className="text-center mb-10">
        
        <h1 className="text-4xl font-bold text-gray-900 mb-2">
          Companies CA Login
        </h1>
        <p className="text-gray-600 text-base">
          Company Chartered Accountant Access Portal
        </p>
      </div>

      {/* Card */}
      <Card className="w-full max-w-md shadow-lg">
        <CardHeader>
          <CardTitle className="text-xxl font-bold">Sign In</CardTitle>
          <CardDescription>
            Use credentials generated by your company dashboard.
          </CardDescription>
        </CardHeader>

        <CardContent>
          <form className="space-y-5" onSubmit={handleLogin}>

            <div className="space-y-1 t">
              <Label htmlFor="company-ca-email" >Email</Label>
              <Input
                id="company-ca-email"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                placeholder="ca@yourcompany.com"
                className="h-11"
                required
              />
            </div>

            <div className="space-y-1">
              <Label htmlFor="company-ca-password">Password</Label>
              <Input
                id="company-ca-password"
                type="password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                placeholder="Your password"
                className="h-11"
                required
              />
            </div>

            {error ? (
              <p className="text-sm text-red-700">{error}</p>
            ) : null}

            <Button
              type="submit"
              className="w-full h-11 text-base"
              disabled={loading}
            >
              {loading ? 'Signing in...' : 'Sign In to Company CA Panel'}
            </Button>
          </form>
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="text-center mt-8 text-sm text-gray-600">
        <p className="inline-flex items-center gap-2">
          © 2026
          <Image
            src="/photos/small-logo.svg"
            alt="Navadrishti logo"
            width={14}
            height={14}
            className="h-3.5 w-3.5"
          />
          Navadrishti Platform
        </p>
        <p className="mt-1">Company CA Management Portal</p>
      </div>

    </div>
  );
}