export { boardCsrAnnexureDraftTemplate, type BoardCsrAnnexureDraftData } from './board-annexure'
export { csrComplianceProfileTemplate, type CsrComplianceProfileData } from './compliance-profile'
export { impactReportTemplate, type ImpactReportData } from './impact-report'
export { implementingAgencyReportTemplate, type ImplementingAgencyReportData } from './implementing-agency'
export { ngoCompliancePackTemplate, type NgoCompliancePackData } from './ngo-compliance-pack'
export type { ImpactReportMilestone } from './shared'
export { utilizationCertificateTemplate, type UtilizationCertificateData } from './utilization-certificate'
